allowBuilds:
  canvas: false
  esbuild: true
  msw: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
  vite-plus: 0.1.24
minimumReleaseAgeExclude:
  - cpd-darwin-arm64@5.0.10
  - cpd-darwin-x64@5.0.10
  - cpd-linux-arm64-gnu@5.0.10
  - cpd-linux-x64-gnu@5.0.10
  - cpd-linux-x64-musl@5.0.10
  - cpd-windows-x64-msvc@5.0.10
  - jscpd@5.0.10
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
