/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QrcodeRouteImport } from './routes/qrcode'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinspaceRouteImport } from './routes/joinspace'
import { Route as ForgetpasswordRouteImport } from './routes/forgetpassword'
import { Route as BindRouteImport } from './routes/bind'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthSummaryRouteImport } from './routes/_auth.summary'
import { Route as AuthSpacesettingsRouteImport } from './routes/_auth.spacesettings'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthPersonadetailRouteImport } from './routes/_auth.personadetail'
import { Route as AuthPersonaRouteImport } from './routes/_auth.persona'
import { Route as AuthMeinfoRouteImport } from './routes/_auth.meinfo'
import { Route as AuthMatterRouteImport } from './routes/_auth.matter'
import { Route as AuthContactsRouteImport } from './routes/_auth.contacts'
import { Route as AuthAppbotRouteImport } from './routes/_auth.appbot'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QrcodeRoute = QrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinspaceRoute = JoinspaceRouteImport.update({
  id: '/joinspace',
  path: '/joinspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgetpasswordRoute = ForgetpasswordRouteImport.update({
  id: '/forgetpassword',
  path: '/forgetpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const BindRoute = BindRouteImport.update({
  id: '/bind',
  path: '/bind',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSummaryRoute = AuthSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSpacesettingsRoute = AuthSpacesettingsRouteImport.update({
  id: '/spacesettings',
  path: '/spacesettings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPersonadetailRoute = AuthPersonadetailRouteImport.update({
  id: '/personadetail',
  path: '/personadetail',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPersonaRoute = AuthPersonaRouteImport.update({
  id: '/persona',
  path: '/persona',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeinfoRoute = AuthMeinfoRouteImport.update({
  id: '/meinfo',
  path: '/meinfo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMatterRoute = AuthMatterRouteImport.update({
  id: '/matter',
  path: '/matter',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsRoute = AuthContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppbotRoute = AuthAppbotRouteImport.update({
  id: '/appbot',
  path: '/appbot',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/bind': typeof BindRoute
  '/forgetpassword': typeof ForgetpasswordRoute
  '/joinspace': typeof JoinspaceRoute
  '/login': typeof LoginRoute
  '/qrcode': typeof QrcodeRoute
  '/register': typeof RegisterRoute
  '/appbot': typeof AuthAppbotRoute
  '/contacts': typeof AuthContactsRoute
  '/matter': typeof AuthMatterRoute
  '/meinfo': typeof AuthMeinfoRoute
  '/persona': typeof AuthPersonaRoute
  '/personadetail': typeof AuthPersonadetailRoute
  '/settings': typeof AuthSettingsRoute
  '/spacesettings': typeof AuthSpacesettingsRoute
  '/summary': typeof AuthSummaryRoute
}
export interface FileRoutesByTo {
  '/bind': typeof BindRoute
  '/forgetpassword': typeof ForgetpasswordRoute
  '/joinspace': typeof JoinspaceRoute
  '/login': typeof LoginRoute
  '/qrcode': typeof QrcodeRoute
  '/register': typeof RegisterRoute
  '/appbot': typeof AuthAppbotRoute
  '/contacts': typeof AuthContactsRoute
  '/matter': typeof AuthMatterRoute
  '/meinfo': typeof AuthMeinfoRoute
  '/persona': typeof AuthPersonaRoute
  '/personadetail': typeof AuthPersonadetailRoute
  '/settings': typeof AuthSettingsRoute
  '/spacesettings': typeof AuthSpacesettingsRoute
  '/summary': typeof AuthSummaryRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/bind': typeof BindRoute
  '/forgetpassword': typeof ForgetpasswordRoute
  '/joinspace': typeof JoinspaceRoute
  '/login': typeof LoginRoute
  '/qrcode': typeof QrcodeRoute
  '/register': typeof RegisterRoute
  '/_auth/appbot': typeof AuthAppbotRoute
  '/_auth/contacts': typeof AuthContactsRoute
  '/_auth/matter': typeof AuthMatterRoute
  '/_auth/meinfo': typeof AuthMeinfoRoute
  '/_auth/persona': typeof AuthPersonaRoute
  '/_auth/personadetail': typeof AuthPersonadetailRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/spacesettings': typeof AuthSpacesettingsRoute
  '/_auth/summary': typeof AuthSummaryRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bind'
    | '/forgetpassword'
    | '/joinspace'
    | '/login'
    | '/qrcode'
    | '/register'
    | '/appbot'
    | '/contacts'
    | '/matter'
    | '/meinfo'
    | '/persona'
    | '/personadetail'
    | '/settings'
    | '/spacesettings'
    | '/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bind'
    | '/forgetpassword'
    | '/joinspace'
    | '/login'
    | '/qrcode'
    | '/register'
    | '/appbot'
    | '/contacts'
    | '/matter'
    | '/meinfo'
    | '/persona'
    | '/personadetail'
    | '/settings'
    | '/spacesettings'
    | '/summary'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/bind'
    | '/forgetpassword'
    | '/joinspace'
    | '/login'
    | '/qrcode'
    | '/register'
    | '/_auth/appbot'
    | '/_auth/contacts'
    | '/_auth/matter'
    | '/_auth/meinfo'
    | '/_auth/persona'
    | '/_auth/personadetail'
    | '/_auth/settings'
    | '/_auth/spacesettings'
    | '/_auth/summary'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  BindRoute: typeof BindRoute
  ForgetpasswordRoute: typeof ForgetpasswordRoute
  JoinspaceRoute: typeof JoinspaceRoute
  LoginRoute: typeof LoginRoute
  QrcodeRoute: typeof QrcodeRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrcode': {
      id: '/qrcode'
      path: '/qrcode'
      fullPath: '/qrcode'
      preLoaderRoute: typeof QrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joinspace': {
      id: '/joinspace'
      path: '/joinspace'
      fullPath: '/joinspace'
      preLoaderRoute: typeof JoinspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgetpassword': {
      id: '/forgetpassword'
      path: '/forgetpassword'
      fullPath: '/forgetpassword'
      preLoaderRoute: typeof ForgetpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bind': {
      id: '/bind'
      path: '/bind'
      fullPath: '/bind'
      preLoaderRoute: typeof BindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/summary': {
      id: '/_auth/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AuthSummaryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/spacesettings': {
      id: '/_auth/spacesettings'
      path: '/spacesettings'
      fullPath: '/spacesettings'
      preLoaderRoute: typeof AuthSpacesettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/personadetail': {
      id: '/_auth/personadetail'
      path: '/personadetail'
      fullPath: '/personadetail'
      preLoaderRoute: typeof AuthPersonadetailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/persona': {
      id: '/_auth/persona'
      path: '/persona'
      fullPath: '/persona'
      preLoaderRoute: typeof AuthPersonaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/meinfo': {
      id: '/_auth/meinfo'
      path: '/meinfo'
      fullPath: '/meinfo'
      preLoaderRoute: typeof AuthMeinfoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/matter': {
      id: '/_auth/matter'
      path: '/matter'
      fullPath: '/matter'
      preLoaderRoute: typeof AuthMatterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts': {
      id: '/_auth/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthContactsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/appbot': {
      id: '/_auth/appbot'
      path: '/appbot'
      fullPath: '/appbot'
      preLoaderRoute: typeof AuthAppbotRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAppbotRoute: typeof AuthAppbotRoute
  AuthContactsRoute: typeof AuthContactsRoute
  AuthMatterRoute: typeof AuthMatterRoute
  AuthMeinfoRoute: typeof AuthMeinfoRoute
  AuthPersonaRoute: typeof AuthPersonaRoute
  AuthPersonadetailRoute: typeof AuthPersonadetailRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSpacesettingsRoute: typeof AuthSpacesettingsRoute
  AuthSummaryRoute: typeof AuthSummaryRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppbotRoute: AuthAppbotRoute,
  AuthContactsRoute: AuthContactsRoute,
  AuthMatterRoute: AuthMatterRoute,
  AuthMeinfoRoute: AuthMeinfoRoute,
  AuthPersonaRoute: AuthPersonaRoute,
  AuthPersonadetailRoute: AuthPersonadetailRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSpacesettingsRoute: AuthSpacesettingsRoute,
  AuthSummaryRoute: AuthSummaryRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  BindRoute: BindRoute,
  ForgetpasswordRoute: ForgetpasswordRoute,
  JoinspaceRoute: JoinspaceRoute,
  LoginRoute: LoginRoute,
  QrcodeRoute: QrcodeRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
