/**
 * Emoji 静态数据(1:1 对齐旧 dmworkbase Service/EmojiService.ts):
 *
 * - key:用户实际插入到 editor 的 token(unicode 字符 或 `[使命必达]` 这种自家 token)
 * - name:对应 png 文件名(如 "0_0" → /emoji/0_0.png),3 个 custom 是命名常量
 *
 * 资源:`public/emoji/${name}.png`(从旧 octo-web/apps/web/public/emoji/ 整目录拷过来)。
 *
 * 自家 custom emoji 走文本 token(`[xxx]`)而不是 unicode — 显示时由消息 renderer
 * 用 emojiRegExp 把 token 替换回 png(P2 后续补 renderer 增强,目前直插文本)。
 */
export interface EmojiItem {
  /** 用户插入到 editor 的 token(unicode 字符 / 自家 [xxx] token) */
  key: string;
  /** 对应 png 文件名(不含扩展名) */
  name: string;
}

export const EMOJI_LIST: EmojiItem[] = [
  { key: "[使命必达]", name: "custom_mission" },
  { key: "[崇尚行动]", name: "custom_action" },
  { key: "[有品位]", name: "custom_taste" },
  { key: "😀", name: "0_0" },
  { key: "😃", name: "0_1" },
  { key: "😄", name: "0_2" },
  { key: "😁", name: "0_3" },
  { key: "😆", name: "0_4" },
  { key: "😅", name: "0_5" },
  { key: "😂", name: "0_6" },
  { key: "🤣", name: "0_7" },
  { key: "🥲", name: "0_8" },
  { key: "☺️", name: "0_9" },
  { key: "😊", name: "0_10" },
  { key: "😇", name: "0_11" },
  { key: "🙂", name: "0_12" },
  { key: "🙃", name: "0_13" },
  { key: "😉", name: "0_14" },
  { key: "😌", name: "0_15" },
  { key: "😍", name: "0_16" },
  { key: "🥰", name: "0_17" },
  { key: "😘", name: "0_18" },
  { key: "😗", name: "0_19" },
  { key: "😙", name: "0_20" },
  { key: "😚", name: "0_21" },
  { key: "😋", name: "0_22" },
  { key: "😛", name: "0_23" },
  { key: "😝", name: "0_24" },
  { key: "😜", name: "0_25" },
  { key: "🤪", name: "0_26" },
  { key: "🤨", name: "0_27" },
  { key: "🧐", name: "0_28" },
  { key: "🤓", name: "0_29" },
  { key: "😎", name: "0_30" },
  { key: "🥸", name: "0_31" },
  { key: "🤩", name: "0_32" },
  { key: "🥳", name: "0_33" },
  { key: "😏", name: "0_34" },
  { key: "😒", name: "0_35" },
  { key: "😞", name: "0_36" },
  { key: "😔", name: "0_37" },
  { key: "😟", name: "0_38" },
  { key: "😕", name: "0_39" },
  { key: "🙁", name: "0_40" },
  { key: "☹️", name: "0_41" },
  { key: "😣", name: "0_42" },
  { key: "😖", name: "0_43" },
  { key: "😫", name: "0_44" },
  { key: "😩", name: "0_45" },
  { key: "🥺", name: "0_46" },
  { key: "😢", name: "0_47" },
  { key: "😭", name: "0_48" },
  { key: "😤", name: "0_49" },
  { key: "😠", name: "0_50" },
  { key: "😡", name: "0_51" },
  { key: "🤬", name: "0_52" },
  { key: "🤯", name: "0_53" },
  { key: "😳", name: "0_54" },
  { key: "🥵", name: "0_55" },
  { key: "🥶", name: "0_56" },
  { key: "😱", name: "0_57" },
  { key: "😨", name: "0_58" },
  { key: "😰", name: "0_59" },
  { key: "😥", name: "0_60" },
  { key: "😓", name: "0_61" },
  { key: "🤗", name: "0_62" },
  { key: "🤔", name: "0_63" },
  { key: "🤭", name: "0_64" },
  { key: "🤫", name: "0_65" },
  { key: "🤥", name: "0_66" },
  { key: "😶", name: "0_67" },
  { key: "😐", name: "0_68" },
  { key: "😑", name: "0_69" },
  { key: "😬", name: "0_70" },
  { key: "🙄", name: "0_71" },
  { key: "😯", name: "0_72" },
  { key: "😦", name: "0_73" },
  { key: "😧", name: "0_74" },
  { key: "😮", name: "0_75" },
  { key: "😲", name: "0_76" },
  { key: "🥱", name: "0_77" },
  { key: "😴", name: "0_78" },
  { key: "🤤", name: "0_79" },
  { key: "😪", name: "0_80" },
  { key: "😵", name: "0_81" },
  { key: "🤐", name: "0_82" },
  { key: "🥴", name: "0_83" },
  { key: "🤢", name: "0_84" },
  { key: "🤮", name: "0_85" },
  { key: "🤧", name: "0_86" },
  { key: "😷", name: "0_87" },
  { key: "🤒", name: "0_88" },
  { key: "🤕", name: "0_89" },
  { key: "🤑", name: "0_90" },
  { key: "🤠", name: "0_91" },
  { key: "😈", name: "0_92" },
  { key: "👿", name: "0_93" },
  { key: "👹", name: "0_94" },
  { key: "👺", name: "0_95" },
  { key: "🤡", name: "0_96" },
  { key: "💩", name: "0_97" },
  { key: "👻", name: "0_98" },
  { key: "💀", name: "0_99" },
  { key: "☠️", name: "0_100" },
  { key: "👽", name: "0_101" },
  { key: "👾", name: "0_102" },
  { key: "🤖", name: "0_103" },
  { key: "🎃", name: "0_104" },
  { key: "😺", name: "0_105" },
  { key: "😸", name: "0_106" },
  { key: "😹", name: "0_107" },
  { key: "😻", name: "0_108" },
  { key: "😼", name: "0_109" },
  { key: "😽", name: "0_110" },
  { key: "🙀", name: "0_111" },
  { key: "😿", name: "0_112" },
  { key: "😾", name: "0_113" },
  { key: "👋", name: "0_114" },
  { key: "🤚", name: "0_115" },
  { key: "🖐", name: "0_116" },
  { key: "✋", name: "0_117" },
  { key: "🖖", name: "0_118" },
  { key: "👌", name: "0_119" },
  { key: "🤌", name: "0_120" },
  { key: "🤏", name: "0_121" },
  { key: "✌️", name: "0_122" },
  { key: "🤞", name: "0_123" },
  { key: "🤟", name: "0_124" },
  { key: "🤘", name: "0_125" },
  { key: "🤙", name: "0_126" },
  { key: "👈", name: "0_127" },
  { key: "👉", name: "0_128" },
  { key: "👆", name: "0_129" },
  { key: "🖕", name: "0_130" },
  { key: "👇", name: "0_131" },
  { key: "☝️", name: "0_132" },
  { key: "👍", name: "0_133" },
  { key: "👎", name: "0_134" },
  { key: "✊", name: "0_135" },
  { key: "👊", name: "0_136" },
  { key: "🤛", name: "0_137" },
  { key: "🤜", name: "0_138" },
  { key: "👏", name: "0_139" },
  { key: "🙌", name: "0_140" },
  { key: "👐", name: "0_141" },
  { key: "🤲", name: "0_142" },
  { key: "🤝", name: "0_143" },
  { key: "🙏", name: "0_144" },
  { key: "✍️", name: "0_145" },
  { key: "💪", name: "0_146" },
  { key: "🦾", name: "0_147" },
  { key: "🦶", name: "0_148" },
  { key: "👂", name: "0_149" },
  { key: "👃", name: "0_150" },
  { key: "💋", name: "0_151" },
];

/** 资源路径(放 public/emoji/,运行时直接 URL 引用)。 */
export function emojiImageUrl(name: string): string {
  return `/emoji/${name}.png`;
}
